version: '3'

services:
    manager:
        # build:
        #     context: .
        #     dockerfile: manager/Dockerfile
        # image: hinemos-manager
        image: aminami1127/hinemos-manager
        volumes:
            - hinemos-data:/opt/hinemos/var/data/
        hostname: centos_manager
        networks:
            hinemos_net:
                ipv4_address: 172.31.1.10
        container_name: hinemos-manager

    agent:
        # build:
        #     context: .
        #     dockerfile: agent/Dockerfile
        # image: hinemos-agent
        image: aminami1127/hinemos-agent
        hostname: centos_node
        networks:
            hinemos_net:
                ipv4_address: 172.31.1.11
        container_name: hinemos-agent

    web:
        # build:
        #     context: .
        #     dockerfile: web/Dockerfile
        # image: hinemos-web
        image: aminami1127/hinemos-web
        ports:
            - '80:80'
        hostname: centos_web
        networks:
            hinemos_net:
                ipv4_address: 172.31.1.12
        container_name: hinemos-web

volumes:
    hinemos-data:

networks:
    hinemos_net:
        ipam:
            driver: default
            config:
                - subnet: 172.31.1.0/24
